/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Upcoming bookings for all event types, one list ordered by `startAt` ascending. */
        get: operations["AdminRoutes_listUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List event types for management. */
        get: operations["AdminRoutes_listEventTypesAdmin"];
        put?: never;
        /** @description Create an event type. */
        post: operations["AdminRoutes_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Delete an event type. Implementations may reject if future bookings exist. */
        delete: operations["AdminRoutes_deleteEventType"];
        options?: never;
        head?: never;
        /** @description Update an event type. */
        patch: operations["AdminRoutes_updateEventType"];
        trace?: never;
    };
    "/public/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a booking. Fails if the interval overlaps any existing booking. */
        post: operations["GuestRoutes_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List event types (name, description, duration) for the booking options page. */
        get: operations["GuestRoutes_listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{eventTypeId}/available-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Free slots for the given type within the default **14-day** booking window from the server’s current date (inclusive).
         *
         *     Slots honor `durationMinutes`, exclude time covered by **any** booking (all types), and align with `CreateBookingRequest.startAt`. */
        get: operations["GuestRoutes_listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BadRequest: {
            /** @enum {string} */
            error: "VALIDATION_ERROR" | "SLOT_OUTSIDE_WINDOW" | "SLOT_MISMATCH";
            message: string;
        };
        /**
         * @description Confirmed booking on [startAt, endAt).
         * @example {
         *       "id": "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
         *       "eventTypeId": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
         *       "eventTypeName": "Product demo",
         *       "startAt": "2026-04-22T15:00:00.000Z",
         *       "endAt": "2026-04-22T15:15:00.000Z",
         *       "guestDisplayName": "Alex Kim"
         *     }
         */
        Booking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            eventTypeId: string;
            eventTypeName: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            guestDisplayName?: string;
        };
        Conflict: {
            /** @enum {string} */
            error: "SLOT_OCCUPIED";
            message: string;
        };
        /** @description Guest books a slot. `startAt` must match a returned free slot start for that event type. */
        CreateBookingRequest: {
            /** Format: uuid */
            eventTypeId: string;
            /** Format: date-time */
            startAt: string;
            /** @description Optional label in the owner’s meeting list. */
            guestDisplayName?: string;
        };
        DeleteEventTypeConflict: {
            /** @enum {string} */
            error: "FUTURE_BOOKINGS_EXIST";
            message: string;
        };
        /**
         * @description Allowed slot length: quarter-hour blocks up to one hour (for Prism mocks and real APIs).
         * @enum {number}
         */
        EventDurationMinutes: 15 | 30 | 45 | 60;
        /**
         * @description Bookable meeting template: identity, copy, and slot length.
         * @example {
         *       "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
         *       "name": "Product demo",
         *       "description": "A 15-minute walkthrough for new customers.",
         *       "durationMinutes": 15
         *     }
         */
        EventType: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** @description Duration of one slot, in minutes (15, 30, 45, or 60 only). */
            durationMinutes: components["schemas"]["EventDurationMinutes"];
        };
        /** @description Create an event type. */
        EventTypeCreate: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            durationMinutes: components["schemas"]["EventDurationMinutes"];
        };
        /** @description Partial update for an event type. */
        EventTypeUpdate: {
            name?: string;
            description?: string;
            durationMinutes?: components["schemas"]["EventDurationMinutes"];
        };
        InternalError: {
            message: string;
        };
        NotFound: {
            message: string;
        };
        /**
         * @description A free interval the guest may book.
         * @example {
         *       "startAt": "2026-04-22T15:00:00.000Z",
         *       "endAt": "2026-04-22T15:15:00.000Z"
         *     }
         */
        TimeSlot: {
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminRoutes_listUpcomingBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    AdminRoutes_listEventTypesAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    AdminRoutes_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    AdminRoutes_deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteEventTypeConflict"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    AdminRoutes_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    GuestRoutes_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conflict"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    GuestRoutes_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    GuestRoutes_listAvailableSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example [
                     *       {
                     *         "startAt": "2026-04-22T15:00:00.000Z",
                     *         "endAt": "2026-04-22T15:15:00.000Z"
                     *       },
                     *       {
                     *         "startAt": "2026-04-22T16:00:00.000Z",
                     *         "endAt": "2026-04-22T16:15:00.000Z"
                     *       }
                     *     ] */
                    "application/json": components["schemas"]["TimeSlot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
}
